In [1]:
import pandas as pd

filename='.\class_eng.xlsx'

df=pd.read_excel(filename,header=2)

cond=df['序号'].notnull()
df=df[cond]

df=df.astype({'学号':int})

var_list=['序号', '学号', '姓名', '班级']

df_new=df[var_list]

<>:3: SyntaxWarning: invalid escape sequence '\c'
<>:3: SyntaxWarning: invalid escape sequence '\c'
C:\Users\mo_xi\AppData\Local\Temp\ipykernel_40340\2889217526.py:3: SyntaxWarning: invalid escape sequence '\c'
  filename='.\class_eng.xlsx'

In [2]:
data_original = {
    '序号': [18, 5, 19, 8, 15, 16, 6, 10, 1, 11, 9, 7, 17, 14, 2, 4, 3, 13, 12],
    '学号': [2023200744, 2021200697, 2023200793, 2022202560, 2023200584, 2023200660, 2021200715, 2022202650, 2021200567, 2022202670, 2022202622, 2022200230, 2023200739, 2023200579, 2021200631, 2021200641, 2021200639, 2022202751, 2022202690],
    '姓名': ['秦梓珂', '柳任时', '江智睿', '卢俊然', '张亦佳', '段毅', '李嘉乐', '李昕珏', '赵一铭', '宋晓明', '薛佳易', '妙含笑', '钟梓洋', '王锦川', '方至成', '林亦隆', '邱丹绮', '张雷臻', '王煜阳'],
    '班级': ['2023经济学类4班', '2021经济学3班', '2023经济学类1班', '2022经济学类4班', '2023经济学类4班', '2023经济学类4班', '2021经济学2班', '2022经济学类2班', '2021经济学1班', '2022经济学类2班', '2022经济学类2班', '2022级本科金融工程班', '2023经济学类3班', '2023经济学类3班', '2021经济学-数学双学位实验班', '2021经济学3班', '2021国际经济与贸易1班', '2022经济学类3班', '2022经济学类4班'],
    'number': [0, 1, 2, 3, 4, 5, 6, 7, 11, 10, 9, 8, 12, 13, 14, 15, 16, 17, 18],
    'group': [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5]
}
df_original = pd.DataFrame(data_original)

common_students = df_new[df_new['学号'].isin(df_original['学号'])]

merged_df = pd.merge(common_students, df_original[['学号', 'group']], on='学号', how='left')

In [3]:
new_students = df_new[~df_new['学号'].isin(df_original['学号'])]

new_students = new_students.sample(frac=1, random_state=202503).reset_index(drop=True)

new_students.loc[0, 'group'] = 2

available_groups = [1, 2, 3, 5]  

selected_groups = pd.Series(available_groups).sample(n=2, random_state=202503).values

new_students.loc[1, 'group'] = selected_groups[0]

new_students.loc[2, 'group'] = selected_groups[1]

final_df = pd.concat([merged_df, new_students], ignore_index=True)

final_df.loc[final_df['姓名'] == '方至成', 'group'] = 6.0
final_df.loc[final_df['姓名'] == '林亦隆', 'group'] = 6.0
final_df.loc[final_df['姓名'] == '赵一铭', 'group'] = 5.0
final_df.loc[final_df['姓名'] == '王煜阳', 'group'] = 3.0
final_df.loc[final_df['姓名'] == '陈相安', 'group'] = 2.0
final_df = final_df.sort_values(by='group')

In [4]:
final_df

      序号          学号   姓名                班级  group
14  18.0  2023200793  江智睿        2023经济学类1班    1.0
4    5.0  2021200697  柳任时         2021经济学3班    1.0
6    7.0  2022202560  卢俊然        2022经济学类4班    1.0
15  17.0  2023200773  钱彦均        2023经济学类1班    2.0
16  10.0  2022202703  陈相安        2022经济学类3班    2.0
12  15.0  2023200660   段毅        2023经济学类4班    2.0
11  14.0  2023200584  张亦佳        2023经济学类4班    2.0
8    9.0  2022202690  王煜阳        2022经济学类4班    3.0
5    6.0  2022200230  妙含笑      2022级本科金融工程班    3.0
7    8.0  2022202622  薛佳易        2022经济学类2班    3.0
13  16.0  2023200739  钟梓洋        2023经济学类3班    4.0
10  13.0  2023200579  王锦川        2023经济学类3班    4.0
0    1.0  2021200567  赵一铭         2021经济学1班    5.0
2    3.0  2021200639  邱丹绮     2021国际经济与贸易1班    5.0
9   11.0  2022202751  张雷臻        2022经济学类3班    5.0
17  12.0  2022202777  晏子晗        2022经济学类1班    5.0
3    4.0  2021200641  林亦隆         2021经济学3班    6.0
1    2.0  2021200631  方至成  2021经济学-数学双学位实验班    6.0