### 整体看看

In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
xiaoqu = pd.read_csv("/home/mw/input/quant4533/ruc_Class25Q1_details.csv")
xiaoqu.head()

,区县,名称,城市,板块,环线位置,小区地址,物业类别,建筑年代,开发商,房屋总数,...,产权描述,供水,供暖,供电,燃气费,供热费,停车位,停车费用,coord_x,coord_y
0,0.0,三峡医专学苑新村,2,9.0,NaN,天星路345号,普通住宅,NaN,NaN,458户,...,商品房,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.452045,30.760940
1,0.0,宁静苑,2,9.0,NaN,天津路138号,普通住宅,NaN,NaN,80户,...,商品房,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.413352,30.770431
2,0.0,电信小区,2,9.0,NaN,沙龙路三段1111号,普通住宅,NaN,NaN,102户,...,商品房,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.406400,30.779299
3,2.0,三元街甲19号院,0,470.0,二至三环,三元街甲19号院,普通住宅,1970-1979年,北京城市开发股份有限公司,103户,...,商品房/已购公房/限价商品房,民水,集中供暖,民电,2.61元/m³,24元/㎡,36.0,150,116.403428,39.876490
4,2.0,东交民巷11号院,0,126.0,二环内,东交民巷东交民巷11号院,普通住宅,1975-1984年,无开发商,222户,...,商品房/已购公房,民水,集中供暖,民电,2.61元/m³,24-30元/㎡,NaN,暂无,116.420030,39.908949

In [3]:
xiaoqu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3100 entries, 0 to 3099
Data columns (total 27 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   区县       3099 non-null   float64
 1   名称       3100 non-null   object
 2   城市       3100 non-null   int64
 3   板块       3095 non-null   float64
 4   环线位置     1802 non-null   object
 5   小区地址     3100 non-null   object
 6   物业类别     3100 non-null   object
 7   建筑年代     2912 non-null   object
 8   开发商      2576 non-null   object
 9   房屋总数     3100 non-null   object
 10  楼栋总数     3100 non-null   object
 11  物业公司     2445 non-null   object
 12  绿 化 率    2714 non-null   object
 13  容 积 率    2717 non-null   float64
 14  物 业 费    2744 non-null   object
 15  建筑结构     2957 non-null   object
 16  物业办公电话   977 non-null    object
 17  产权描述     3098 non-null   object
 18  供水       2913 non-null   object
 19  供暖       2366 non-null   object
 20  供电       2930 non-null   object
 21  燃气费      2668 non-null   object
 22  供热费      1235 non-null   object
 23  停车位      2546 non-null   float64
 24  停车费用     2665 non-null   object
 25  coord_x  3100 non-null   float64
 26  coord_y  3100 non-null   float64
dtypes: float64(6), int64(1), object(20)
memory usage: 654.0+ KB

In [4]:
has_duplicates = xiaoqu['名称'].duplicated().any()
if has_duplicates:
    print("'名称' 列存在重复信息。")
else:
    print("'名称' 列不存在重复信息。")

# 查看具体的重复数量
duplicate_count = xiaoqu['名称'].duplicated().sum()
print(f"'名称' 列的重复数量为: {duplicate_count}")

# 查看具体的重复行
duplicate_rows = xiaoqu[xiaoqu['名称'].duplicated(keep=False)]
print("具体的重复行信息如下:")
print(duplicate_rows)

'名称' 列存在重复信息。
'名称' 列的重复数量为: 127
具体的重复行信息如下:
         区县       名称  城市     板块  环线位置  \
1       0.0      宁静苑   2    9.0   NaN
2       0.0     电信小区   2    9.0   NaN
50      2.0     阳光都市   0  334.0  二至三环
67      3.0      桃花源   4  102.0  三至四环
81      3.0    龙湖新壹城   4  102.0  三至四环
...     ...      ...  ..    ...   ...
3050   99.0     职教小区   1  759.0   NaN
3052   99.0     阳光家园   1  759.0   NaN
3073  101.0    新世纪大厦   3  608.0   内环内
3074  101.0  日月光伯爵天地   3  393.0   NaN
3080  101.0     福海小区   3   91.0   内环内

                                          小区地址        物业类别        建筑年代  \
1                                      天津路138号        普通住宅         NaN
2                                   沙龙路三段1111号        普通住宅         NaN
50                                      新中街18号        普通住宅  2000-2003年
67                                    生物园西路18号        普通住宅  2010-2016年
81                                   神墩一路龙湖新壹城   普通住宅/商住两用       2019年
...                                        ...         ...         ...
3050                                   新华大街99号        普通住宅  1990-2000年
3052                                      阳光家园        普通住宅  2000-2006年
3073                                 陆家浜路1011号  普通住宅/商业办公类       2003年
3074                              浦秀路1536弄157号  车库/普通住宅/商业  2000-2014年
3080  温州路11弄,温州路41弄,温州路49弄,黄河路238弄,黄河路240-244号        普通住宅  1974-1979年

                   开发商   房屋总数  ...     产权描述     供水    供暖     供电        燃气费  \
1                  NaN    80户  ...      商品房    NaN   NaN    NaN        NaN
2                  NaN   102户  ...      商品房    NaN   NaN    NaN        NaN
50    北京华居工体北房地产开发有限公司   947户  ...   商品房/私产     民水  集中供暖     民电   2.61元/m³
67          武汉光谷地产有限公司  2424户  ...      商品房     民水  集中供暖     民电   2.53元/m³
81          武汉京文置业有限公司  1461户  ...      商品房  商水/民水   自采暖  商电/民电        NaN
...                ...    ...  ...      ...    ...   ...    ...        ...
3050            三强实业集团    40户  ...      商品房     民水  集中供暖     民电   2.48元/m³
3052            三强实业集团   276户  ...      商品房     民水  集中供暖     民电   2.46元/m³
3073     上海新世纪大厦发展有限公司   437户  ...      商品房     商水   NaN     商电      3元/m³
3074               NaN  1824户  ...  商品房/使用权  商水/民水   自采暖  商电/民电  2.5-3元/m³
3080        上海华商房产发展公司   288户  ...  商品房/使用权     民水   NaN     民电        NaN

           供热费     停车位                   停车费用     coord_x    coord_y
1          NaN     NaN                    NaN  108.413352  30.770431
2          NaN     NaN                    NaN  108.406400  30.779299
50    24-30元/㎡  1010.0  地上车位500元/月，地下车位600元/月  116.447331  39.941506
67         NaN   711.0                    135  114.542707  30.483866
81         NaN  1200.0                    450  114.515413  30.491395
...        ...     ...                    ...         ...        ...
3050     25元/㎡   150.0                    500  117.003473  39.769808
3052     25元/㎡    50.0                    200  117.017111  39.751578
3073       NaN    60.0                    100  121.495746  31.218347
3074       NaN     NaN                    300  121.484692  31.224686
3080       NaN     NaN                     暂无  121.476357  31.243188

[223 rows x 27 columns]

In [5]:
xiaoqu = xiaoqu.drop_duplicates(subset=['名称'])

In [6]:
xiaoqu.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2973 entries, 0 to 3099
Data columns (total 27 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   区县       2972 non-null   float64
 1   名称       2973 non-null   object
 2   城市       2973 non-null   int64
 3   板块       2968 non-null   float64
 4   环线位置     1730 non-null   object
 5   小区地址     2973 non-null   object
 6   物业类别     2973 non-null   object
 7   建筑年代     2793 non-null   object
 8   开发商      2468 non-null   object
 9   房屋总数     2973 non-null   object
 10  楼栋总数     2973 non-null   object
 11  物业公司     2344 non-null   object
 12  绿 化 率    2603 non-null   object
 13  容 积 率    2602 non-null   float64
 14  物 业 费    2630 non-null   object
 15  建筑结构     2837 non-null   object
 16  物业办公电话   942 non-null    object
 17  产权描述     2972 non-null   object
 18  供水       2798 non-null   object
 19  供暖       2273 non-null   object
 20  供电       2812 non-null   object
 21  燃气费      2564 non-null   object
 22  供热费      1190 non-null   object
 23  停车位      2440 non-null   float64
 24  停车费用     2555 non-null   object
 25  coord_x  2973 non-null   float64
 26  coord_y  2973 non-null   float64
dtypes: float64(6), int64(1), object(20)
memory usage: 650.3+ KB

### 数据处理

In [7]:
#绿化率：改变数据类型、去除超过100%的异常值（已知无其他异常值）、用中位数填充空的
xiaoqu['绿 化 率'] = xiaoqu['绿 化 率'].apply(lambda x: float(x[:-1]) if pd.notna(x) else x)
xiaoqu['绿 化 率'] = xiaoqu['绿 化 率'].where((xiaoqu['绿 化 率'].isnull()) | (xiaoqu['绿 化 率'] <= 100), None)
xiaoqu['绿 化 率'].fillna(xiaoqu['绿 化 率'].median(), inplace=True)

#容积率：用中位数填充
xiaoqu['容 积 率'].fillna(xiaoqu['容 积 率'].median(), inplace=True)

#房屋总数：转换类型
xiaoqu['房屋总数'] = xiaoqu['房屋总数'].apply(lambda x: int(x[:-1]) if pd.notna(x) else x)

#楼栋总数：转换类型
xiaoqu['楼栋总数'] = xiaoqu['楼栋总数'].apply(lambda x: int(x[:-1]) if pd.notna(x) else x)

停车问题

In [8]:
filtered_df = xiaoqu[xiaoqu['停车位'] > 5000]

# 打印筛选后的结果
print(filtered_df[['物业类别','房屋总数','停车位']])

                                         物业类别  房屋总数      停车位
76                        普通住宅/写字楼/商业/商住两用/底商  3711   6141.0
631                                      普通住宅  2600   5533.0
642                                普通住宅/商业/底商  4893   6000.0
871                                      普通住宅   603   7166.0
1042  普通住宅/写字楼/商业/底商/商业办公类/酒店式公寓/公寓（住宅）/公寓/住宅  1374   5200.0
1444                                     普通住宅  4620   5924.0
1675                                     普通住宅  2913   5680.0
1973                                     普通住宅   224  16600.0
2551                                     普通住宅  1322   9830.0
2552                                     普通住宅   386   9800.0
2662                            车库/普通住宅/商业/底商  1827   6219.0

In [9]:
#结合上述信息，把几个拥有太多停车位的普通住宅按照一户两车进行填充
xiaoqu.loc[[871,1973,2551,2552], '停车位'] = xiaoqu.loc[[871,1973,2551,2552], '房屋总数']*2
#把nan填充为0
xiaoqu['停车位'] = xiaoqu['停车位'].fillna(0)
xiaoqu['停车位'].describe()

count    2973.000000
mean      447.196435
std       694.477508
min         0.000000
25%        32.000000
50%       200.000000
75%       509.000000
max      6219.000000
Name: 停车位, dtype: float64

In [10]:
#处理建筑年代
def process_cell(cell):
    if pd.isna(cell):
        return cell
    two_years = re.findall(r'\d+', cell)
    if len(two_years) == 2:
        year1, year2 = map(int, two_years)

        #把2024年以后的年份视为异常值处理。
        if year1 > 2024 and year2 > 2024:
            return None
        elif year1 > 2024:
            return float(year2)
        elif year2 > 2024:
            return float(year1)
        return (year1 + year2) / 2
    elif len(two_years) == 1:
        year = int(two_years[0])

        #把2024年以后的年份视为异常值处理。
        if year > 2024:
            return None
        return float(year)
    return cell

xiaoqu['建筑年代'] = xiaoqu['建筑年代'].apply(process_cell)
#用中位数填充空值
xiaoqu['建筑年代'].fillna(xiaoqu['建筑年代'].median(), inplace=True)

In [11]:
#丢弃不需要的列
xiaoqu.drop(['区县', '城市','板块','小区地址','物业类别','开发商','建筑结构','物业办公电话','产权描述'], axis=1, inplace=True)

In [13]:
#停车费用处理
new_data = []
for fee in xiaoqu['停车费用']:
    if pd.isnull(fee) or fee == '0' or fee == '0.0' or fee == '0.00' or fee == '0.000000000000000000000' or fee == '暂无' or fee == '无' or fee == '免费' or fee == '-':
        new_data.append(0)
    elif isinstance(fee, str):
        nums = [float(s) for s in fee.split() if s.isdigit() or s.replace('.', '', 1).isdigit()]
        if nums:
            new_data.append(np.mean(nums))
        else:
            new_data.append(0)
    else:
        new_data.append(float(fee))

# 将处理后的数据替换原列数据
xiaoqu['停车费用'] = new_data

In [14]:
xiaoqu.to_csv('/home/mw/project/xiaoqu.csv', index=False)